# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'العربية')], default='en-us', max_length=10, verbose_name='Language'),
        ),
    ]
