# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20170725_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('language', 'order')]),
        ),
    ]
