# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20170731_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
