# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'العربية')], default='en-us', max_length=10, verbose_name='Language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
