# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ranking_question', '0001_initial'),
        ('radio_question', '0001_initial'),
        ('selection_question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField(verbose_name='Choice')),
                ('radio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='radio_question.RadioQuestion')),
                ('rank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_question.RankingQuestion')),
                ('selection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='selection_question.SelectionQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, verbose_name='Choice Type')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice.Type'),
        ),
    ]
