# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-01 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0002_auto_20170808_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='type',
        ),
        migrations.AddField(
            model_name='choice',
            name='image_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Image url'),
        ),
    ]
