# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 10:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0003_questionnaire_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(verbose_name='Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Last updated time')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.Questionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
