# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-05 01:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingquestion',
            name='multiplier',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=1.0, verbose_name='Multiplier'), default=[1], size=None),
            preserve_default=False,
        ),
    ]
