# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
