# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20170807_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'العربية')], default='en-us', max_length=10, verbose_name='Language'),
        ),
    ]
