# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-01 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_questionnaire_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionorder',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Question order'),
        ),
    ]
