# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-01 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20180401_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation time'),
            preserve_default=False,
        ),
    ]
